import type { Gene } from '../types';

/**
 * The canonical list of all known Ball Python genes.
 *
 * To add a new gene, append an entry here following the existing pattern.
 * Fields: id (snake_case), name (display), shortName (≤4 chars), type, category.
 * For codominant genes, also set superName. Set lethalSuper: true when applicable.
 */
export const GENES: Gene[] = [
  { id: '210_hypo', name: '210 Hypo', shortName: '21Hy', type: 'recessive', category: 'Recessive' },
  { id: 'albino', name: 'Albino', shortName: 'Alb', type: 'recessive', category: 'Recessive' },
  { id: 'amur', name: 'Amur', shortName: 'Amur', type: 'recessive', category: 'Recessive' },
  { id: 'atomic', name: 'Atomic', shortName: 'Atom', type: 'recessive', category: 'Recessive' },
  { id: 'axanthic_gcr', name: 'Axanthic (GCR)', shortName: 'AxGc', type: 'recessive', category: 'Recessive' },
  { id: 'axanthic_jolliff', name: 'Axanthic (Jolliff)', shortName: 'AxJo', type: 'recessive', category: 'Recessive' },
  { id: 'axanthic_mj', name: 'Axanthic (MJ)', shortName: 'AxMj', type: 'recessive', category: 'Recessive' },
  { id: 'axanthic_srp', name: 'Axanthic (SRP)', shortName: 'AxSr', type: 'recessive', category: 'Recessive' },
  { id: 'axanthic_tsk', name: 'Axanthic (TSK)', shortName: 'AxTs', type: 'recessive', category: 'Recessive' },
  { id: 'axanthic_vpi', name: 'Axanthic (VPI)', shortName: 'AxVp', type: 'recessive', category: 'Recessive' },
  { id: 'banded_bantah', name: 'Banded (Bantah)', shortName: 'BaBa', type: 'recessive', category: 'Recessive' },
  { id: 'bengal', name: 'Bengal', shortName: 'Beng', type: 'recessive', category: 'Recessive' },
  { id: 'black_axanthic', name: 'Black Axanthic', shortName: 'BlAx', type: 'recessive', category: 'Recessive' },
  { id: 'black_lace', name: 'Black Lace', shortName: 'BlLa', type: 'recessive', category: 'Recessive' },
  { id: 'bourgogne_albino', name: 'Bourgogne Albino', shortName: 'BoAl', type: 'recessive', category: 'Recessive' },
  { id: 'burgundy', name: 'Burgundy', shortName: 'Burg', type: 'recessive', category: 'Recessive' },
  { id: 'candy', name: 'Candy', shortName: 'Can', type: 'recessive', category: 'Recessive' },
  { id: 'caramel_albino', name: 'Caramel Albino', shortName: 'CarA', type: 'recessive', category: 'Recessive' },
  { id: 'citrus_hypo', name: 'Citrus Hypo', shortName: 'CiHy', type: 'recessive', category: 'Recessive' },
  { id: 'clown', name: 'Clown', shortName: 'Clown', type: 'recessive', category: 'Recessive' },
  { id: 'crider', name: 'Crider', shortName: 'Crid', type: 'recessive', category: 'Recessive' },
  { id: 'cryptic', name: 'Cryptic', shortName: 'Cryp', type: 'recessive', category: 'Recessive' },
  { id: 'd_stripe', name: 'D-stripe', shortName: 'D-st', type: 'recessive', category: 'Recessive' },
  { id: 'daddy', name: 'Daddy', shortName: 'Dadd', type: 'recessive', category: 'Recessive' },
  { id: 'dark_matter', name: 'Dark Matter', shortName: 'DaMa', type: 'recessive', category: 'Recessive' },
  { id: 'desert_ghost', name: 'Desert Ghost', shortName: 'DG', type: 'recessive', category: 'Recessive' },
  { id: 'enhancer', name: 'Enhancer', shortName: 'Enha', type: 'recessive', category: 'Recessive' },
  { id: 'genetic_stripe', name: 'Genetic Stripe', shortName: 'GS', aliases: ['G-Stripe', 'G Stripe'], type: 'recessive', category: 'Recessive' },
  { id: 'ghost_vesper', name: 'Ghost (Vesper)', shortName: 'GhV', type: 'recessive', category: 'Recessive' },
  { id: 'gizmo', name: 'Gizmo', shortName: 'Gizm', type: 'recessive', category: 'Recessive' },
  { id: 'goldfinger', name: 'Goldfinger', shortName: 'Gold', type: 'recessive', category: 'Recessive' },
  { id: 'green_ghost', name: 'Green Ghost', shortName: 'GrG', type: 'recessive', category: 'Recessive' },
  { id: 'hypo', name: 'Hypo', shortName: 'Hyp', type: 'recessive', category: 'Recessive' },
  { id: 'kmr_tri_stripe', name: 'KMR Tri Stripe', shortName: 'KmTr', type: 'recessive', category: 'Recessive' },
  { id: 'lavender_albino', name: 'Lavender Albino', shortName: 'Lav', type: 'recessive', category: 'Recessive' },
  { id: 'maple', name: 'Maple', shortName: 'Mapl', type: 'recessive', category: 'Recessive' },
  { id: 'matriarch', name: 'Matriarch', shortName: 'Matr', type: 'recessive', category: 'Recessive' },
  { id: 'metal_flake', name: 'Metal Flake', shortName: 'MeFl', type: 'recessive', category: 'Recessive' },
  { id: 'migraine', name: 'Migraine', shortName: 'Migr', type: 'recessive', category: 'Recessive' },
  { id: 'monarch', name: 'Monarch', shortName: 'Mona', type: 'recessive', category: 'Recessive' },
  { id: 'monsoon', name: 'Monsoon', shortName: 'Mon', type: 'recessive', category: 'Recessive' },
  { id: 'moray', name: 'Moray', shortName: 'Mora', type: 'recessive', category: 'Recessive' },
  { id: 'neo', name: 'Neo', shortName: 'Neo', type: 'recessive', category: 'Recessive' },
  { id: 'orange_crush', name: 'Orange Crush', shortName: 'OrCr', type: 'recessive', category: 'Recessive' },
  { id: 'orange_ghost', name: 'Orange Ghost', shortName: 'OrG', type: 'recessive', category: 'Recessive' },
  { id: 'paint', name: 'Paint', shortName: 'Pain', type: 'recessive', category: 'Recessive' },
  { id: 'patternless', name: 'Patternless', shortName: 'Patt', type: 'recessive', category: 'Recessive' },
  { id: 'piebald', name: 'Piebald', shortName: 'Pied', type: 'recessive', category: 'Recessive' },
  { id: 'puzzle', name: 'Puzzle', shortName: 'Puzz', type: 'recessive', category: 'Recessive' },
  { id: 'reco', name: 'RECO', shortName: 'RECO', type: 'recessive', category: 'Recessive' },
  { id: 'rainbow', name: 'Rainbow', shortName: 'Rain', type: 'recessive', category: 'Recessive' },
  { id: 'red_axanthic', name: 'Red Axanthic', shortName: 'ReAx', type: 'recessive', category: 'Recessive' },
  { id: 'rust', name: 'Rust', shortName: 'Rust', type: 'recessive', category: 'Recessive' },
  { id: 'sahara', name: 'Sahara', shortName: 'Saha', type: 'recessive', category: 'Recessive' },
  { id: 'sentinel', name: 'Sentinel', shortName: 'Sent', type: 'recessive', category: 'Recessive' },
  { id: 'sunset', name: 'Sunset', shortName: 'Suns', type: 'recessive', category: 'Recessive' },
  { id: 'sunset_tcr', name: 'Sunset (TCR)', shortName: 'SuTc', type: 'recessive', category: 'Recessive' },
  { id: 'toffee', name: 'Toffee', shortName: 'Tof', type: 'recessive', category: 'Recessive' },
  { id: 'tornado', name: 'Tornado', shortName: 'Torn', type: 'recessive', category: 'Recessive' },
  { id: 'tri_stripe', name: 'Tri-stripe', shortName: 'Tri-', type: 'recessive', category: 'Recessive' },
  { id: 'ultramel', name: 'Ultramel', shortName: 'Ult', type: 'recessive', category: 'Recessive' },
  { id: 'whitewash', name: 'Whitewash', shortName: 'Whit', type: 'recessive', category: 'Recessive' },
  { id: 'zebra', name: 'Zebra', shortName: 'Zebr', type: 'recessive', category: 'Recessive' },
  { id: 'ahi', name: 'AHI', shortName: 'AHI', type: 'codominant', category: 'Co-Dominant' },
  { id: 'acid', name: 'Acid', shortName: 'Aci', type: 'codominant', category: 'Co-Dominant' },
  { id: 'adder', name: 'Adder', shortName: 'Adde', type: 'codominant', category: 'Co-Dominant' },
  { id: 'ajax', name: 'Ajax', shortName: 'Ajax', type: 'codominant', category: 'Co-Dominant' },
  { id: 'alloy', name: 'Alloy', shortName: 'Allo', type: 'codominant', category: 'Co-Dominant' },
  { id: 'alpha', name: 'Alpha', shortName: 'Alph', type: 'codominant', category: 'Co-Dominant' },
  { id: 'ambush', name: 'Ambush', shortName: 'Ambu', type: 'codominant', category: 'Co-Dominant' },
  { id: 'arcane', name: 'Arcane', shortName: 'Arca', type: 'codominant', category: 'Co-Dominant' },
  { id: 'arid', name: 'Arid', shortName: 'Arid', type: 'codominant', category: 'Co-Dominant' },
  { id: 'arroyo', name: 'Arroyo', shortName: 'Arro', type: 'codominant', category: 'Co-Dominant' },
  { id: 'ashen', name: 'Ashen', shortName: 'Ashe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'asphalt', name: 'Asphalt', shortName: 'Asp', type: 'codominant', category: 'Co-Dominant' },
  { id: 'astro', name: 'Astro', shortName: 'Astr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'aurora', name: 'Aurora', shortName: 'Auro', type: 'codominant', category: 'Co-Dominant' },
  { id: 'avalanche', name: 'Avalanche', shortName: 'Aval', type: 'codominant', category: 'Co-Dominant' },
  { id: 'bald', name: 'Bald', shortName: 'Bald', type: 'codominant', category: 'Co-Dominant' },
  { id: 'bambino', name: 'Bambino', shortName: 'Bamb', type: 'codominant', category: 'Co-Dominant' },
  { id: 'bamboo', name: 'Bamboo', shortName: 'Bamb', type: 'codominant', category: 'Co-Dominant' },
  { id: 'banana', name: 'Banana', shortName: 'Ban', type: 'codominant', category: 'Co-Dominant' },
  { id: 'bang', name: 'Bang', shortName: 'Bang', type: 'codominant', category: 'Co-Dominant' },
  { id: 'barnhart_black_pastel', name: 'Barnhart Black Pastel', shortName: 'BaBl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'biancaball', name: 'Biancaball', shortName: 'Bian', type: 'codominant', category: 'Co-Dominant' },
  { id: 'bingo', name: 'Bingo', shortName: 'Bing', type: 'codominant', category: 'Co-Dominant' },
  { id: 'black_belly', name: 'Black Belly', shortName: 'BkB', type: 'codominant', category: 'Co-Dominant' },
  { id: 'black_head', name: 'Black Head', shortName: 'BkH', type: 'codominant', category: 'Co-Dominant' },
  { id: 'black_opal', name: 'Black Opal', shortName: 'BlOp', type: 'codominant', category: 'Co-Dominant' },
  { id: 'black_pastel', name: 'Black Pastel', shortName: 'BP', type: 'codominant', category: 'Co-Dominant' },
  { id: 'blade', name: 'Blade', shortName: 'Blad', type: 'codominant', category: 'Co-Dominant' },
  { id: 'bling_yellow_belly', name: 'Bling Yellow Belly', shortName: 'BlYe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'blitz', name: 'Blitz', shortName: 'Blit', type: 'codominant', category: 'Co-Dominant' },
  { id: 'bongo', name: 'Bongo', shortName: 'Bong', type: 'codominant', category: 'Co-Dominant' },
  { id: 'brite', name: 'Brite', shortName: 'Brit', type: 'codominant', category: 'Co-Dominant' },
  { id: 'brown_back', name: 'Brown Back', shortName: 'BrBa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'butter', name: 'Butter', shortName: 'Btr', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'cafe', name: 'Cafe', shortName: 'Cafe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'cajun', name: 'Cajun', shortName: 'Caju', type: 'codominant', category: 'Co-Dominant' },
  { id: 'calico', name: 'Calico', shortName: 'Cali', type: 'codominant', category: 'Co-Dominant' },
  { id: 'cantaloupe', name: 'Cantaloupe', shortName: 'Cant', type: 'codominant', category: 'Co-Dominant' },
  { id: 'carbon', name: 'Carbon', shortName: 'Carb', type: 'codominant', category: 'Co-Dominant' },
  { id: 'carnivore', name: 'Carnivore', shortName: 'Carn', type: 'codominant', category: 'Co-Dominant' },
  { id: 'champagne', name: 'Champagne', shortName: 'Chm', type: 'codominant', lethalSuper: true, riskNote: 'Champagne carries neurological wobble — consult a specialist before breeding.', category: 'Co-Dominant' },
  { id: 'chino', name: 'Chino', shortName: 'Chin', type: 'codominant', category: 'Co-Dominant' },
  { id: 'chocolate', name: 'Chocolate', shortName: 'Choc', type: 'codominant', category: 'Co-Dominant' },
  { id: 'cinder', name: 'Cinder', shortName: 'Cind', type: 'codominant', category: 'Co-Dominant' },
  { id: 'cinnamon', name: 'Cinnamon', shortName: 'Cin', type: 'codominant', category: 'Co-Dominant' },
  { id: 'circle', name: 'Circle', shortName: 'Circ', type: 'codominant', category: 'Co-Dominant' },
  { id: 'citron', name: 'Citron', shortName: 'Citr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'citrus_pastel', name: 'Citrus Pastel', shortName: 'CiPa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'cloud', name: 'Cloud', shortName: 'Clou', type: 'codominant', category: 'Co-Dominant' },
  { id: 'cocoa', name: 'Cocoa', shortName: 'Coco', type: 'codominant', category: 'Co-Dominant' },
  { id: 'coffee', name: 'Coffee', shortName: 'Coff', type: 'codominant', category: 'Co-Dominant' },
  { id: 'confusion', name: 'Confusion', shortName: 'Conf', type: 'codominant', category: 'Co-Dominant' },
  { id: 'congo', name: 'Congo', shortName: 'Cong', type: 'codominant', category: 'Co-Dominant' },
  { id: 'copper', name: 'Copper', shortName: 'Copp', type: 'codominant', category: 'Co-Dominant' },
  { id: 'coral_glow', name: 'Coral Glow', shortName: 'CG', type: 'codominant', category: 'Co-Dominant' },
  { id: 'creed', name: 'Creed', shortName: 'Cree', type: 'codominant', category: 'Co-Dominant' },
  { id: 'cypress', name: 'Cypress', shortName: 'Cypr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'dark_angel', name: 'Dark Angel', shortName: 'DaAn', type: 'codominant', category: 'Co-Dominant' },
  { id: 'dark_viking', name: 'Dark Viking', shortName: 'DaVi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'darkside_gold', name: 'Darkside Gold', shortName: 'DaGo', type: 'codominant', category: 'Co-Dominant' },
  { id: 'desert', name: 'Desert', shortName: 'Dese', type: 'codominant', category: 'Co-Dominant' },
  { id: 'diesel', name: 'Diesel', shortName: 'Dies', type: 'codominant', category: 'Co-Dominant' },
  { id: 'disco', name: 'Disco', shortName: 'Disc', type: 'codominant', category: 'Co-Dominant' },
  { id: 'dot', name: 'Dot', shortName: 'Dot', type: 'codominant', category: 'Co-Dominant' },
  { id: 'emg', name: 'EMG', shortName: 'EMG', type: 'codominant', category: 'Co-Dominant' },
  { id: 'ember', name: 'Ember', shortName: 'Embe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'enchi', name: 'Enchi', shortName: 'Enc', type: 'codominant', category: 'Co-Dominant' },
  { id: 'epic', name: 'Epic', shortName: 'Epic', type: 'codominant', category: 'Co-Dominant' },
  { id: 'eramosa', name: 'Eramosa', shortName: 'Eram', type: 'codominant', category: 'Co-Dominant' },
  { id: 'exo_lbb', name: 'Exo-lbb', shortName: 'Exo-', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'fnr_vanilla', name: 'FNR Vanilla', shortName: 'FnVa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'fire', name: 'Fire', shortName: 'Fir', type: 'codominant', category: 'Co-Dominant' },
  { id: 'flame', name: 'Flame', shortName: 'Flam', type: 'codominant', category: 'Co-Dominant' },
  { id: 'flare', name: 'Flare', shortName: 'Flar', type: 'codominant', category: 'Co-Dominant' },
  { id: 'frost', name: 'Frost', shortName: 'Fros', type: 'codominant', category: 'Co-Dominant' },
  { id: 'furrow', name: 'Furrow', shortName: 'Furr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'fusion', name: 'Fusion', shortName: 'Fusi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'ghi', name: 'GHI', shortName: 'GHI', type: 'codominant', category: 'Co-Dominant' },
  { id: 'gaia', name: 'Gaia', shortName: 'Gaia', type: 'codominant', category: 'Co-Dominant' },
  { id: 'gallium', name: 'Gallium', shortName: 'Gall', type: 'codominant', category: 'Co-Dominant' },
  { id: 'garcia', name: 'Garcia', shortName: 'Garc', type: 'codominant', category: 'Co-Dominant' },
  { id: 'genex', name: 'GeneX', shortName: 'Gene', type: 'codominant', category: 'Co-Dominant' },
  { id: 'genetic_banded', name: 'Genetic Banded', shortName: 'GB', type: 'codominant', category: 'Co-Dominant' },
  { id: 'glossy', name: 'Glossy', shortName: 'Glos', type: 'codominant', category: 'Co-Dominant' },
  { id: 'gobi', name: 'Gobi', shortName: 'Gobi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'goblin', name: 'Goblin', shortName: 'Gobl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'gold_blush', name: 'Gold Blush', shortName: 'GoBl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'gorilla', name: 'Gorilla', shortName: 'Gori', type: 'codominant', category: 'Co-Dominant' },
  { id: 'granite', name: 'Granite', shortName: 'Gran', type: 'codominant', category: 'Co-Dominant' },
  { id: 'gravel', name: 'Gravel', shortName: 'Grv', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'grim', name: 'Grim', shortName: 'Grim', type: 'codominant', category: 'Co-Dominant' },
  { id: 'gypsy', name: 'Gypsy', shortName: 'Gyps', type: 'codominant', category: 'Co-Dominant' },
  { id: 'harlequin', name: 'Harlequin', shortName: 'Harl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'hellfire', name: 'Hellfire', shortName: 'Hell', type: 'codominant', category: 'Co-Dominant' },
  { id: 'hetari', name: 'Hetari', shortName: 'Heta', type: 'codominant', category: 'Co-Dominant' },
  { id: 'hidden_gene_woma', name: 'Hidden Gene Woma', shortName: 'HGW', type: 'codominant', category: 'Co-Dominant' },
  { id: 'hieroglyphic', name: 'Hieroglyphic', shortName: 'Hier', type: 'codominant', category: 'Co-Dominant' },
  { id: 'high_intensity_od', name: 'High Intensity OD', shortName: 'HiIn', type: 'codominant', category: 'Co-Dominant' },
  { id: 'high_orange_gene', name: 'High Orange Gene', shortName: 'HiOr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'honey', name: 'Honey', shortName: 'Hone', type: 'codominant', category: 'Co-Dominant' },
  { id: 'huffman', name: 'Huffman', shortName: 'Huff', type: 'codominant', category: 'Co-Dominant' },
  { id: 'hurricane', name: 'Hurricane', shortName: 'Hurr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'hydra', name: 'Hydra', shortName: 'Hydr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'iconic', name: 'Iconic', shortName: 'Icon', type: 'codominant', category: 'Co-Dominant' },
  { id: 'jaguar', name: 'Jaguar', shortName: 'Jagu', type: 'codominant', category: 'Co-Dominant' },
  { id: 'java', name: 'Java', shortName: 'Java', type: 'codominant', category: 'Co-Dominant' },
  { id: 'jedi', name: 'Jedi', shortName: 'Jedi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'jolliff_tiger', name: 'Jolliff Tiger', shortName: 'JoTi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'jolt', name: 'Jolt', shortName: 'Jolt', type: 'codominant', category: 'Co-Dominant' },
  { id: 'joppa', name: 'Joppa', shortName: 'Jopp', type: 'codominant', category: 'Co-Dominant' },
  { id: 'josie', name: 'Josie', shortName: 'Josi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'jungle_woma', name: 'Jungle Woma', shortName: 'JuWo', type: 'codominant', lethalSuper: true, category: 'Co-Dominant' },
  { id: 'krg', name: 'KRG', shortName: 'KRG', type: 'codominant', category: 'Co-Dominant' },
  { id: 'kosmos', name: 'Kosmos', shortName: 'Kosm', type: 'codominant', category: 'Co-Dominant' },
  { id: 'lc_black_magic', name: 'LC Black Magic', shortName: 'LcBl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'lace', name: 'Lace', shortName: 'Lace', type: 'codominant', category: 'Co-Dominant' },
  { id: 'lace_black_back', name: 'Lace Black Back', shortName: 'LaBl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'lemon_pastel', name: 'Lemon Pastel', shortName: 'LePa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'lemonback', name: 'Lemonback', shortName: 'Lemo', type: 'codominant', category: 'Co-Dominant' },
  { id: 'leopard', name: 'Leopard', shortName: 'Leo', type: 'codominant', category: 'Co-Dominant' },
  { id: 'lesser', name: 'Lesser', shortName: 'Les', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'lori', name: 'Lori', shortName: 'Lori', type: 'codominant', category: 'Co-Dominant' },
  { id: 'lucifer', name: 'Lucifer', shortName: 'Luci', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mahogany', name: 'Mahogany', shortName: 'Maho', type: 'codominant', category: 'Co-Dominant' },
  { id: 'malum', name: 'Malum', shortName: 'Malu', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mancer', name: 'Mancer', shortName: 'Manc', type: 'codominant', category: 'Co-Dominant' },
  { id: 'marble', name: 'Marble', shortName: 'Marb', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mario', name: 'Mario', shortName: 'Mari', type: 'codominant', category: 'Co-Dominant' },
  { id: 'marvel', name: 'Marvel', shortName: 'Marv', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mckenzie', name: 'Mckenzie', shortName: 'Mcke', type: 'codominant', category: 'Co-Dominant' },
  { id: 'melt', name: 'Melt', shortName: 'Melt', type: 'codominant', category: 'Co-Dominant' },
  { id: 'microscale', name: 'Microscale', shortName: 'Micr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mocha', name: 'Mocha', shortName: 'Moch', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mojave', name: 'Mojave', shortName: 'Moj', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'mordor', name: 'Mordor', shortName: 'Mord', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mosaic', name: 'Mosaic', shortName: 'Mosa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mota', name: 'Mota', shortName: 'Mota', type: 'codominant', category: 'Co-Dominant' },
  { id: 'motley', name: 'Motley', shortName: 'Motl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'mystic', name: 'Mystic', shortName: 'Mys', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'nanny', name: 'Nanny', shortName: 'Nann', type: 'codominant', category: 'Co-Dominant' },
  { id: 'napalm', name: 'Napalm', shortName: 'Napa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'nazca', name: 'Nazca', shortName: 'Nazc', type: 'codominant', category: 'Co-Dominant' },
  { id: 'neon', name: 'Neon', shortName: 'Neon', type: 'codominant', category: 'Co-Dominant' },
  { id: 'nico', name: 'Nico', shortName: 'Nico', type: 'codominant', category: 'Co-Dominant' },
  { id: 'nova', name: 'Nova', shortName: 'Nova', type: 'codominant', category: 'Co-Dominant' },
  { id: 'nr_mandarin', name: 'Nr Mandarin', shortName: 'NrMa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'nyala', name: 'Nyala', shortName: 'Nyal', type: 'codominant', category: 'Co-Dominant' },
  { id: 'ofy', name: 'OFY', shortName: 'OFY', type: 'codominant', category: 'Co-Dominant' },
  { id: 'odium', name: 'Odium', shortName: 'Odiu', type: 'codominant', category: 'Co-Dominant' },
  { id: 'orange_belly', name: 'Orange Belly', shortName: 'OrBe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'orange_dream', name: 'Orange Dream', shortName: 'OD', type: 'codominant', category: 'Co-Dominant' },
  { id: 'orange_glow', name: 'Orange Glow', shortName: 'OrGl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'orbit', name: 'Orbit', shortName: 'Orbi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'oriole', name: 'Oriole', shortName: 'Orio', type: 'codominant', category: 'Co-Dominant' },
  { id: 'panther', name: 'Panther', shortName: 'Pant', type: 'codominant', category: 'Co-Dominant' },
  { id: 'pastel', name: 'Pastel', shortName: 'Pas', type: 'codominant', category: 'Co-Dominant' },
  { id: 'patternless_x', name: 'Patternless X', shortName: 'PaX', type: 'codominant', category: 'Co-Dominant' },
  { id: 'peach', name: 'Peach', shortName: 'Peac', type: 'codominant', category: 'Co-Dominant' },
  { id: 'phantom', name: 'Phantom', shortName: 'Pha', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'phenomenon', name: 'Phenomenon', shortName: 'Phen', type: 'codominant', category: 'Co-Dominant' },
  { id: 'philistine', name: 'Philistine', shortName: 'Phil', type: 'codominant', category: 'Co-Dominant' },
  { id: 'pixel', name: 'Pixel', shortName: 'Pixe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'quake', name: 'Quake', shortName: 'Quak', type: 'codominant', category: 'Co-Dominant' },
  { id: 'rar', name: 'RAR', shortName: 'RAR', type: 'codominant', category: 'Co-Dominant' },
  { id: 'rk_asphalt', name: 'RK Asphalt', shortName: 'RkAs', type: 'codominant', category: 'Co-Dominant' },
  { id: 'radioactive', name: 'Radioactive', shortName: 'Radi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'rain', name: 'Rain', shortName: 'Rain', type: 'codominant', category: 'Co-Dominant' },
  { id: 'raven', name: 'Raven', shortName: 'Rave', type: 'codominant', category: 'Co-Dominant' },
  { id: 'razor', name: 'Razor', shortName: 'Razo', type: 'codominant', category: 'Co-Dominant' },
  { id: 'reaper', name: 'Reaper', shortName: 'Reap', type: 'codominant', category: 'Co-Dominant' },
  { id: 'red_gene', name: 'Red Gene', shortName: 'ReGe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'red_stripe', name: 'Red Stripe', shortName: 'RS', type: 'codominant', category: 'Co-Dominant' },
  { id: 'redhead', name: 'Redhead', shortName: 'Redh', type: 'codominant', category: 'Co-Dominant' },
  { id: 'rhino', name: 'Rhino', shortName: 'Rhin', type: 'codominant', category: 'Co-Dominant' },
  { id: 'russo', name: 'Russo', shortName: 'Rus', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'saar', name: 'Saar', shortName: 'Saar', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sable', name: 'Sable', shortName: 'Sabl', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sabre', name: 'Sabre', shortName: 'Sabr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sandblast', name: 'Sandblast', shortName: 'Sand', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sandstorm', name: 'Sandstorm', shortName: 'Sand', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sapphire', name: 'Sapphire', shortName: 'Sapp', type: 'codominant', category: 'Co-Dominant' },
  { id: 'satin', name: 'Satin', shortName: 'Sati', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sauce', name: 'Sauce', shortName: 'Sauc', type: 'codominant', category: 'Co-Dominant' },
  { id: 'scaleless_head', name: 'Scaleless Head', shortName: 'ScHe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'scrambler', name: 'Scrambler', shortName: 'Scra', type: 'codominant', category: 'Co-Dominant' },
  { id: 'shadow', name: 'Shadow', shortName: 'Shad', type: 'codominant', category: 'Co-Dominant' },
  { id: 'shatter', name: 'Shatter', shortName: 'Shat', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sherg', name: 'Sherg', shortName: 'Sher', type: 'codominant', category: 'Co-Dominant' },
  { id: 'shinobi', name: 'Shinobi', shortName: 'Shin', type: 'codominant', category: 'Co-Dominant' },
  { id: 'shrapnel', name: 'Shrapnel', shortName: 'Shra', type: 'codominant', category: 'Co-Dominant' },
  { id: 'shredder', name: 'Shredder', shortName: 'Shre', type: 'codominant', category: 'Co-Dominant' },
  { id: 'silver_ghost', name: 'Silver Ghost', shortName: 'SiGh', type: 'codominant', category: 'Co-Dominant' },
  { id: 'smoke', name: 'Smoke', shortName: 'Smok', type: 'codominant', category: 'Co-Dominant' },
  { id: 'smuggler', name: 'Smuggler', shortName: 'Smug', type: 'codominant', category: 'Co-Dominant' },
  { id: 'solar', name: 'Solar', shortName: 'Sola', type: 'codominant', category: 'Co-Dominant' },
  { id: 'spark', name: 'Spark', shortName: 'Spar', type: 'codominant', category: 'Co-Dominant' },
  { id: 'special', name: 'Special', shortName: 'Spc', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'special_noco', name: 'Special (NoCo)', shortName: 'SpNo', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'special_tcr', name: 'Special (TCR)', shortName: 'SpTc', type: 'codominant', superName: 'Blue Eyed Leucistic', category: 'BEL Complex' },
  { id: 'specter', name: 'Specter', shortName: 'Spec', type: 'codominant', category: 'Co-Dominant' },
  { id: 'spider', name: 'Spider', shortName: 'Spi', type: 'codominant', lethalSuper: true, riskNote: 'Spider carries neurological wobble (corkscrewing) — consult a specialist before breeding.', category: 'Co-Dominant' },
  { id: 'splash', name: 'Splash', shortName: 'Spla', type: 'codominant', category: 'Co-Dominant' },
  { id: 'splatter', name: 'Splatter', shortName: 'Spla', type: 'codominant', category: 'Co-Dominant' },
  { id: 'spotnose', name: 'Spotnose', shortName: 'SN', type: 'codominant', category: 'Co-Dominant' },
  { id: 'static', name: 'Static', shortName: 'Stat', type: 'codominant', category: 'Co-Dominant' },
  { id: 'stranger', name: 'Stranger', shortName: 'Stra', type: 'codominant', category: 'Co-Dominant' },
  { id: 'striker', name: 'Striker', shortName: 'Stri', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sugar', name: 'Sugar', shortName: 'Sug', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sulfur', name: 'Sulfur', shortName: 'Sulf', type: 'codominant', category: 'Co-Dominant' },
  { id: 'sunrise', name: 'Sunrise', shortName: 'Sunr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'surge', name: 'Surge', shortName: 'Surg', type: 'codominant', category: 'Co-Dominant' },
  { id: 'tango', name: 'Tango', shortName: 'Tang', type: 'codominant', category: 'Co-Dominant' },
  { id: 'taronja', name: 'Taronja', shortName: 'Taro', type: 'codominant', category: 'Co-Dominant' },
  { id: 'the_darkling', name: 'The Darkling', shortName: 'ThDa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'tolosa', name: 'Tolosa', shortName: 'Tolo', type: 'codominant', category: 'Co-Dominant' },
  { id: 'toxique', name: 'Toxique', shortName: 'Toxi', type: 'codominant', category: 'Co-Dominant' },
  { id: 'trick', name: 'Trick', shortName: 'Tric', type: 'codominant', category: 'Co-Dominant' },
  { id: 'trident', name: 'Trident', shortName: 'Trid', type: 'codominant', category: 'Co-Dominant' },
  { id: 'trojan', name: 'Trojan', shortName: 'Troj', type: 'codominant', category: 'Co-Dominant' },
  { id: 'turbo', name: 'Turbo', shortName: 'Turb', type: 'codominant', category: 'Co-Dominant' },
  { id: 'twister', name: 'Twister', shortName: 'Twis', type: 'codominant', category: 'Co-Dominant' },
  { id: 'vanilla', name: 'Vanilla', shortName: 'Van', type: 'codominant', category: 'Co-Dominant' },
  { id: 'vesper', name: 'Vesper', shortName: 'Vesp', type: 'codominant', category: 'Co-Dominant' },
  { id: 'victory', name: 'Victory', shortName: 'Vict', type: 'codominant', category: 'Co-Dominant' },
  { id: 'vudoo', name: 'Vudoo', shortName: 'Vudo', type: 'codominant', category: 'Co-Dominant' },
  { id: 'web', name: 'Web', shortName: 'Web', type: 'codominant', category: 'Co-Dominant' },
  { id: 'whitesmoke', name: 'Whitesmoke', shortName: 'Whit', type: 'codominant', category: 'Co-Dominant' },
  { id: 'woma', name: 'Woma', shortName: 'Wom', type: 'codominant', lethalSuper: true, riskNote: 'Woma is associated with neurological wobble in some lines — consult a specialist before breeding.', category: 'Co-Dominant' },
  { id: 'wookie', name: 'Wookie', shortName: 'Wook', type: 'codominant', category: 'Co-Dominant' },
  { id: 'wrecking_ball', name: 'Wrecking Ball', shortName: 'WrBa', type: 'codominant', category: 'Co-Dominant' },
  { id: 'x_treme_gene', name: 'X-treme Gene', shortName: 'X-Ge', type: 'codominant', category: 'Co-Dominant' },
  { id: 'x_tremist', name: 'X-tremist', shortName: 'X-tr', type: 'codominant', category: 'Co-Dominant' },
  { id: 'xremist', name: 'Xremist', shortName: 'Xrem', type: 'codominant', category: 'Co-Dominant' },
  { id: 'yellow_belly', name: 'Yellow Belly', shortName: 'YB', type: 'codominant', superName: 'Ivory', category: 'Co-Dominant' },
  { id: 'zip_belly', name: 'Zip Belly', shortName: 'ZiBe', type: 'codominant', category: 'Co-Dominant' },
  { id: 'zuwadi', name: 'Zuwadi', shortName: 'Zuwa', type: 'codominant', category: 'Co-Dominant' },

  // ── Dominant genes ────────────────────────────────────────────────────────
  // 1 copy = visual; 2 copies = visually identical to 1 copy (no distinct super form).
  // Lethal dominant genes are flagged with lethalSuper: true.
  { id: 'pinstripe', name: 'Pinstripe', shortName: 'Pin', type: 'dominant', category: 'Dominant' },
  { id: 'scaleless', name: 'Scaleless', shortName: 'Scls', type: 'dominant', lethalSuper: true, riskNote: 'Scaleless homozygous is lethal — do not breed two Scaleless together.', category: 'Dominant' },
  { id: 'ultramel_dom', name: 'Ultramel (Dom)', shortName: 'UltD', type: 'dominant', category: 'Dominant' },
];

